feat: restore `passOnConnectionError` option
express-rate-limit/rate-limit-redis pull request #193
Opened 2023-09-13 16:35 UTC by gamemaker1

This PR closes #190.

It works like a charm with an `ioredis` client. However, the `node-redis` client is a bit stubborn when it comes to reconnecting - it waits for the server to reconnect forever. If you use [a custom `retryStrategy`](https://stackoverflow.com/questions/66666210/node-redis-does-retry-strategy-have-a-default-value) that tells it to stop after x retries, it will stop and not attempt to reconnect, even during the next time `increment` is called. I haven't yet figured out a workaround for that.

2023-09-13 16:40 UTC, gamemaker1 commented
@nfriedly @abhijeetviswa Please do review this PR and let me know if I should make any changes.

2023-09-13 18:14 UTC, nfriedly requested changes
Hey @gamemaker1 , sorry I didn't think of this before you did all this work, but I think the `passOnConnectionError` option should be in express-rate-limit, rather than here, so that it can be used with any store. I think the store itself should just throw an error.

2023-09-13 18:14 UTC, nfriedly commented on source/lib.ts
> +			throw new TypeError('Expected result to be the script SHA')
```suggestion
			throw new TypeError(`Expected result of SCRIPT LOAD command to be the script SHA, got ${result}`)
```

2023-09-15 04:54 UTC, gamemaker1 commented
Oh all right that makes sense

2023-09-16 08:52 UTC, abhijeetviswa approved these changes
The changes itself looks good. I'll leave the design discussions to y'all. Thanks

2024-07-23 15:37 UTC, closed without merging